version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always  # Make sure this is correctly indented

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always  # Ensure it's properly formatted

  flask_app:
    image: flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=development # or production
    depends_on:
      - prometheus
      - node_exporter
    volumes:
      - ./flask_app:/app
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set a default admin password
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
    driver: local
networks:
  default:
    driver: bridge
    # You can specify other network settings here if needed
    # For example, you can set a specific subnet or gateway if required   