pipeline {
    agent any
    
    environment {
        VENV_DIR = 'venv'
    }
    
    triggers {
        githubPush()
    }
    
    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/yashraj7878/DevOps_Internship_Challenge.git'
            }
        }
        
        stage('Setup Dependencies') {
            steps {
                sh '''
                cd flask_app
                python3 -m venv $VENV_DIR
                source $VENV_DIR/bin/activate
                pip install -r requirements.txt
                '''
            }
        }
        
        stage('Restart Service') {
            steps {
                sh 'sudo systemctl restart flask_app'
            }
        }
        
        stage('Test Application') {
            steps {
                sh 'curl -s http://localhost:5000/ || exit 1'
            }
        }
    }
    
    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed! Check logs.'
        }
    }
}
